name: run rest-assured api tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
 builds:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v4.1.1

   - name: Setup Java JDK 17
     uses: actions/setup-java@v3.13.0
     with:
       java-version: 17

   - name: Cache Maven packages
     uses: actions/cache@v3.3.2
     with:
          path: ~/.m2/repository  # Cache the Maven repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}  # Cache key based on the OS and project files
          restore-keys: |
            maven-${{ runner.os }}-

   - name: Run Tests
     run: mvn clean test
   
